openapi: 3.0.0
info:
  title: IceKathon Api
  version: '1.0'
  description: IceKathon API Doc
  contact:
    name: Agus Budianto
    email: agus.kbk@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  /auth/login:
    post:
      summary: Login
      operationId: post-auth-login
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '422':
          $ref: '#/components/responses/422'
      tags:
        - auth
      description: User Login Endpoint
      parameters:
        - $ref: '#/components/parameters/Content-Type'
      requestBody:
        $ref: '#/components/requestBodies/LoginRequest'
components:
  schemas: {}
  requestBodies:
    LoginRequest:
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              email:
                type: string
                minLength: 1
              password:
                type: string
                minLength: 1
            required:
              - email
              - password
            x-examples:
              example-1:
                email: user@icehousecorp.com
                password: user password
          examples:
            Login Request Example:
              $ref: '#/components/examples/LoginRequestExample'
      description: Login Request
  examples:
    LoginRequestExample:
      value:
        email: user@icehousecorp.com
        password: user password
    200Resp:
      value:
        success: true
    ErrorResp:
      value:
        code: Err-XX
        message: error messages
    422Resp:
      value:
        fields:
          fieldname1: ''
          fieldname2: ''
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
  responses:
    '200':
      description: Succes Response
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
          examples:
            SuccesResponseExample:
              $ref: '#/components/examples/200Resp'
        application/xml:
          schema:
            description: ''
            type: object
            properties:
              success:
                type: boolean
            required:
              - success
            x-examples:
              example-1:
                success: true
      headers: {}
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - code
              - message
            x-examples:
              example-1:
                code: ''
                message: ''
          examples:
            BadReqeustExample:
              $ref: '#/components/examples/ErrorResp'
      headers: {}
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - code
              - message
            x-examples:
              example-1:
                code: ''
                message: ''
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/ErrorResp'
        application/xml:
          schema:
            type: object
            properties: {}
      headers: {}
    '422':
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
          examples:
            UnprocessibleEntityResponseExample:
              $ref: '#/components/examples/422Resp'
